# Generated by Django 4.2.19 on 2025-02-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Facebook', 'Facebook'), ('Linkedin', 'Linkedin'), ('Instagram', 'Instagram'), ('Youtube', 'Youtube'), ('Tiktok', 'Tiktok'), ('Pinterest', 'Pinterest'), ('Whatsapp', 'Whatsapp'), ('Twitter', 'Twitter')], max_length=20)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='complementary',
            options={'verbose_name_plural': 'complementaries'},
        ),
    ]
