# Generated by Django 4.2.19 on 2025-03-04 06:39

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
