# Generated by Django 4.2.19 on 2025-02-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0002_social_alter_amenities_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Outdoor', 'Outdoor'), ('Dining', 'Dining'), ('Activities', 'Activities'), ('Events', 'Events'), ('Interior', 'Interior'), ('Rooms', 'Rooms')], max_length=20)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
