# Generated by Django 4.2.19 on 2025-02-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='is_read',
            new_name='mark_as_read',
        ),
    ]
