# Generated by Django 4.2.19 on 2025-03-05 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0004_alter_activityimageline_alt_text_alter_blog_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blogs/thumbnail/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='alt_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
