# Generated by Django 4.2.19 on 2025-03-03 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0005_rename_is_read_contact_mark_as_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='venu',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Gazipur', 'Gazipur')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='venu',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Gazipur', 'Gazipur')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Cottage', 'Cottage'), ('Suite', 'Suite'), ('Villa', 'Villa'), ('Duplex', 'Duplex'), ('Lake View', 'Lake View'), ('River View', 'River View'), ('Delux', 'Delux')], max_length=20),
        ),
    ]
