# Generated by Django 4.2.19 on 2025-03-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0006_activity_venu_room_venu_alter_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='venu',
            new_name='venue',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='venu',
            new_name='venue',
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Cottage', 'Cottage'), ('Suite', 'Suite'), ('Villa', 'Villa'), ('Duplex', 'Duplex'), ('Lake View', 'Lake View'), ('River View', 'River View'), ('Deluxe', 'Deluxe')], max_length=20),
        ),
    ]
