# Generated by Django 4.2.19 on 2025-03-13 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0007_paymentmethod_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='account_number',
            new_name='account_no',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='name',
            new_name='method_name',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='ifsc_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='payment_method/qrcode'),
        ),
    ]
