# Generated by Django 4.2.19 on 2025-03-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0007_rename_venu_activity_venue_rename_venu_room_venue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='description',
        ),
        migrations.RemoveField(
            model_name='social',
            name='type',
        ),
        migrations.RemoveField(
            model_name='social',
            name='url',
        ),
        migrations.AddField(
            model_name='social',
            name='facebook',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='instagram',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='linkedin',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='pinterest',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='tiktok',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='twitter',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='youtube',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
