# Generated by Django 4.2.19 on 2025-03-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0008_rename_account_number_paymentmethod_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='payment_method/banner/'),
        ),
    ]
