# Generated by Django 4.2.19 on 2025-03-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0008_remove_social_description_remove_social_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='slogan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
