# Generated by Django 4.2.19 on 2025-03-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0009_alter_paymentmethod_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='transaction/'),
        ),
    ]
