# Generated by Django 4.2.19 on 2025-03-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0011_aboutview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutView',
            new_name='About',
        ),
    ]
