# Generated by Django 4.2.19 on 2025-03-13 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0012_rename_aboutview_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='account_holder',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_name',
            field=models.CharField(choices=[('Bkash', 'Bkash'), ('Rocket', 'Rocket'), ('Nagad', 'Nagad'), ('Upay', 'Upay'), ('Bank', 'Bank'), ('Other', 'Other')], max_length=50),
        ),
    ]
