# Generated by Django 4.2.19 on 2025-03-13 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0013_paymentmethod_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='venue',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Gazipur', 'Gazipur')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
