# Generated by Django 4.2.19 on 2025-03-17 04:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0015_alter_transaction_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='venue/thumbnail/')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('venue', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Gazipur', 'Gazipur')], max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
