# Generated by Django 4.2.19 on 2025-03-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0016_venueinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venueinfo',
            options={'verbose_name_plural': 'Venue Info'},
        ),
        migrations.AlterField(
            model_name='venueinfo',
            name='venue',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Gazipur', 'Gazipur')], max_length=100, unique=True),
        ),
    ]
