# Generated by Django 4.2.19 on 2025-03-18 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0017_alter_venueinfo_options_alter_venueinfo_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Day Long', 'Day Long'), ('Night', 'Night')], max_length=20)),
                ('cost', models.IntegerField()),
                ('is_full_board', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='plan_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resort.plan'),
        ),
    ]
