# Generated by Django 4.2.19 on 2025-03-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0018_plan_booking_plan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='is_full_board',
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('Day Long', 'Day Long'), ('Day Long All-Inclusive', 'Day Long All-Inclusive'), ('Night', 'Night'), ('Night All-Inclusive', 'Night All-Inclusive')], max_length=25),
        ),
    ]
