# Generated by Django 4.2.19 on 2025-03-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0020_remove_plan_cost_plan_extra_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='extra_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
